### ISSUE TITLE
Withdraw all

### ISSUE THREAD

**Issue by sven-hash** [notrustverify/tipALPH#25]
Would it be interesting to be able to withdraw everything in one `/withdraw` command ?

Something like `/withdraw <address>` and then the user will have all of his tokens + ALPH withdrawed

**Comment by amadeous** [comment]
Would need to edit regex to allow "all" instead of amount and token.
Then call new method in Alephium, doing sth similar to https://github.com/alephium/alephium-web3/blob/master/test/exchange.test.ts#L60
